server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/talk?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: talk
    password: talk
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: talk
      password: talk
      database: talk
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  secret: dKWtZatJnhtqIOyd7OqsGMjZhjIrTyyqQzh9LPcUvu5Ynapz

cors:
  url: http://localhost:8080